# Generated by Django 3.2.25 on 2025-02-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0013_alter_video_video_id"),
        ("playlists", "0003_auto_20250212_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="videos",
            field=models.ManyToManyField(
                blank=True, related_name="playlist_item", to="videos.Video"
            ),
        ),
    ]
