# Generated by Django 3.2.25 on 2025-02-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0013_alter_video_video_id"),
        ("playlists", "0004_alter_playlist_videos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlist_featured",
                to="videos.video",
            ),
        ),
    ]
