# Generated by Django 3.2.25 on 2025-02-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0005_alter_playlist_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="videos",
        ),
    ]
