# Generated by Django 3.2.25 on 2025-02-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
