# Generated by Django 3.2.25 on 2025-02-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20250207_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='VideoAdmin',
        ),
    ]
